apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 662c665e805546e88e01f8f49b3f753856f12f39
    app.quarkus.io/build-timestamp: 2021-11-25 - 22:37:06 +0000
  labels:
    app.kubernetes.io/name: summit-demo
    app.kubernetes.io/version: "1.0"
  name: summit-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: summit-demo
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 662c665e805546e88e01f8f49b3f753856f12f39
        app.quarkus.io/build-timestamp: 2021-11-25 - 22:37:06 +0000
      labels:
        app.kubernetes.io/name: summit-demo
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
#            - name: DB_HOST
#              valueFrom: { secretKeyRef: { name: summitdb-pguser-summit, key: host } }                   
#            - name: DB_USER
#              valueFrom: { secretKeyRef: { name: summitdb-pguser-summit, key: user } }
#            - name: DB_PASSWORD
#              valueFrom: { secretKeyRef: { name: summitdb-pguser-summit, key: password } }
#            - name: DB_DATABASE
#              valueFrom: { secretKeyRef: { name: summitdb-pguser-summit, key: dbname } }
          envFrom:
            - configMapRef:
                name: summit-demo
          image: quay.io/wpernath/summit-demo:latest
          imagePullPolicy: Always
          name: summit-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
