apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: stage-
commonLabels:
  variant: stage


# in stage we have 2 replicas
replicas:
- count: 2
  name: summit-demo

# generate a configmap 
configMapGenerator:
- literals:
  - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://summit-db/summitdb
  - QUARKUS_DATASOURCE_USERNAME=summit
  - QUARKUS_DATASOURCE_PASSWORD=summit
  - QUARKUS_DATASOURCE_DB-KIND=postgresql
  name: summit-demo

# replace the image tag of the container with stage
images:
- digest: sha256:23607fa51abcb060a07422eaf198e0adb73ed772b6cde5017f5c597b291d0ae9
  name: quay.io/wpernath/summit-demo:latest
  newName: quay.io/wpernath/summit-demo:v1.1.1

# apply some patches

# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: stage-summit-demo
  target:
    kind: Route
