namePrefix: stage-
commonLabels:
  variant: stage


# in stage we have 2 replicas
replicas:
- count: 2
  name: summit-demo

# generate a configmap 
configMapGenerator:
  - name: summit-demo
    literals:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://summit-stage-db/summitdb
      - QUARKUS_DATASOURCE_USERNAME=summit
      - QUARKUS_DATASOURCE_PASSWORD=summit
      - QUARKUS_DATASOURCE_DB-KIND=postgresql

# replace the image tag of the container with stage
images:
- digest: sha256:892165d2db290ccee45e18d9198f689052859667b8e17307b1ad1fd530572b22
  name: quay.io/wpernath/simple-quarkus:latest
  newName: quay.io/wpernath/summit-demo:v1.0.1

# apply some patches

# this patch needs to be done, because kustomize does not change 
# the route target service name
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: stage-summit-demo
  target:
    kind: Route
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
