namePrefix: stage-  
commonLabels:
  variant: stage

bases:
- ../../base

# in stage we have 2 replicas
replicas:
- name: summit-demo
  count: 2

# replace the image tag of the container with stage
images:
  - name: quay.io/wpernath/summit-demo:latest
    newName: quay.io/wpernath/summit-demo
    newTag: 1.0.0

# apply some patches
patches:

# this patch needs to be done, because kustomize does not change 
# the route target service name
  - patch: |-
      - op: replace
        path: /spec/to/name
        value: stage-summit-demo
    target:
      kind: Route

