apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: dev-
commonLabels:
  variant: development

# generate a configmap 
configMapGenerator:
- literals:
  - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://dev-summit-db/summitdb
  - QUARKUS_DATASOURCE_USERNAME=summit
  - QUARKUS_DATASOURCE_PASSWORD=summit
  - QUARKUS_DATASOURCE_DB-KIND=postgresql
  name: summit-demo

# replace the image tag of the container with latest
images:
- digest: sha256:287d8ed4dda7e679fd3164a15e0b8dc5b8dd4545363f6abca467b87d5abe2311
  name: quay.io/wpernath/summit-demo:latest
  newName: quay.io/wpernath/summit-demo:latest

     
# this patch needs to be done, because kustomize does not change 
# the route target service name

# Patch deploymentConfig of postgresql to reference the correct secret



patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-summit-demo
  target:
    kind: Route
- patch: |-
    - op: replace
      path: /spec/selector/name
      value: dev-summit-db
  target:
    kind: DeploymentConfig
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/name
      value: dev-summit-db
  target:
    kind: DeploymentConfig

- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
      value: dev-summit-db
  target:
    kind: DeploymentConfig
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
      value: dev-summit-db
  target:
    kind: DeploymentConfig
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
      value: dev-summit-db
  target:
    kind: DeploymentConfig
