apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: dev-
commonLabels:
  variant: development

# generate a configmap 
configMapGenerator:
- literals:
  - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://dev-summit-db/summitdb
  - QUARKUS_DATASOURCE_USERNAME=summit
  - QUARKUS_DATASOURCE_PASSWORD=summit
  - QUARKUS_DATASOURCE_DB-KIND=postgresql
  name: summit-demo

# replace the image tag of the container with latest
images:
- digest: sha256:a39da9294165dab0f9bed9b844a1f410b53eecad7e90586f39ff0bf781ec24fa
  name: quay.io/wpernath/summit-demo:latest
  newName: quay.io/wpernath/summit-demo:latest

     
# this patch needs to be done, because kustomize does not change 
# the route target service name

patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-summit-demo
  target:
    kind: Route
