apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namePrefix: dev-
commonLabels:
  variant: development

# generate a configmap 
configMapGenerator:
- literals:
  - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://summit-db/summitdb
  - QUARKUS_DATASOURCE_USERNAME=summit
  - QUARKUS_DATASOURCE_PASSWORD=summit
  - QUARKUS_DATASOURCE_DB-KIND=postgresql
  name: summit-demo

# replace the image tag of the container with latest
images:
- digest: sha256:fa17fd4824c06d72fb813f1a0d659b722a09fe2cc6e912c26cc7eb28dfc55dc4
  name: quay.io/wpernath/summit-demo:latest
  newName: quay.io/wpernath/summit-demo:latest

     
# this patch needs to be done, because kustomize does not change 
# the route target service name

patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-summit-demo
  target:
    kind: Route
